### PR TITLE
More ergonomic paged listing

### PR DESCRIPTION
**Pull request by xbrianh**
This improves the UX experience for retrieving paged listing of storage objects.

A page of results is retrieved with:
```
listing = handle.list_v2(token=None)
page = listing().get_page()
for item in page:
    key = item[0]
next_token = listing.token
```

### CODE REVIEW

**Review by amarjandu — APPROVED** [review]

**Review by Bento007 — APPROVED** [review]
LGTM

**Comment by ttung** [comment]
If you want to make this a great experience, you should just return an iterator across all items, and wrap all the paging details internally.

**Comment by xbrianh** [comment]
@ttung We want to support listings that are paged through a DSS API endpoint. Your recommendations for that use case are extremely welcome.

The status-quo does what you suggest. Maybe that's correct.

**Comment by ttung** [comment]
Oh ha, I remember the use case for this now. So sorry, carry on.

**Comment by xbrianh** [comment]
This functionality is not an improvement over the current API. Closing.

**Pull request closed without merging**
